# Generated by Django 5.1.4 on 2024-12-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_design',
            field=models.FileField(blank=True, null=True, upload_to='custom_designs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(default=list),
        ),
    ]
