# Generated by Django 5.1.4 on 2024-12-27 13:38

import shop_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_cartitem_color_cartitem_custom_design_cartitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.JSONField(default=shop_app.models.default_colors),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.JSONField(default=shop_app.models.default_sizes),
        ),
    ]
