# Generated by Django 5.1.4 on 2024-12-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=100)),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
